# Generated by Django 5.0.1 on 2024-02-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
