# Generated by Django 5.0.1 on 2024-02-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0017_alter_india_img_place'),
        ('guide_app', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('Select_destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.popular')),
                ('Select_destinationskerala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kerala')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travelguide')),
            ],
        ),
    ]
