# Generated by Django 5.0.1 on 2024-02-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
