# Generated by Django 5.0.1 on 2024-03-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
