# Generated by Django 5.0.1 on 2024-03-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_guide_remove_travelguide_user_name'),
        ('guide_app', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guide'),
        ),
    ]
