# Generated by Django 5.0.1 on 2024-03-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0008_alter_bookinginfo_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookinginfo',
        ),
    ]
