# Generated by Django 5.0.1 on 2024-03-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0012_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookinginfo',
        ),
    ]
