# Generated by Django 5.0.1 on 2024-03-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0013_delete_bookinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guide',
            new_name='guide_name',
        ),
    ]
