# Generated by Django 5.0.1 on 2024-03-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0015_guides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guides',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='guides',
            old_name='Password1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='guides',
            old_name='Password2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='guides',
            old_name='user_name',
            new_name='username',
        ),
    ]
