# Generated by Django 5.0.1 on 2024-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0017_delete_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_Email', models.EmailField(max_length=254)),
                ('complaint', models.TextField(max_length=400)),
            ],
        ),
    ]
