# Generated by Django 5.0.1 on 2024-03-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0018_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guide_name',
        ),
    ]
