# Generated by Django 5.0.1 on 2024-03-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0019_remove_booking_guide_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
