# Generated by Django 5.0.1 on 2024-03-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0023_guideprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guide_reg',
        ),
    ]
