# Generated by Django 5.0.1 on 2024-04-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0025_guide_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
