# Generated by Django 5.0.1 on 2024-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0027_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='guide_reg',
            name='profile_image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='profile_imagess'),
        ),
    ]
