# Generated by Django 5.0.1 on 2024-04-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_india_is_favorite_kerala_is_favorite'),
        ('guide_app', '0028_remove_guideprofile_user_guide_reg_profile_image'),
        ('user_app', '0035_delete_direct_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direct_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.guide')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user_app.user_reg')),
            ],
        ),
    ]
