# Generated by Django 5.0.1 on 2024-04-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_india_is_favorite_kerala_is_favorite'),
        ('guide_app', '0030_alter_direct_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct_message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.guide'),
        ),
    ]
