# Generated by Django 5.0.1 on 2024-04-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0031_alter_direct_message_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direct_message',
        ),
    ]
