# Generated by Django 5.0.1 on 2024-04-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_india_is_favorite_kerala_is_favorite'),
        ('guide_app', '0033_direct_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guidename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_app.guide_reg'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide'),
        ),
    ]
