# Generated by Django 5.0.1 on 2024-04-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0035_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Direct_message',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
