# Generated by Django 5.0.1 on 2024-04-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0040_direct_message_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
