# Generated by Django 5.0.1 on 2024-04-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_india_is_favorite_kerala_is_favorite'),
        ('guide_app', '0041_delete_booking'),
        ('user_app', '0049_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('Select_india_destinations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.india')),
                ('Select_kerala_destinations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kerala')),
                ('guide_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.guide')),
                ('guidename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_app.guide_reg')),
                ('select_Popular_destinations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.popular')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_reg')),
            ],
        ),
    ]
