# Generated by Django 5.0.1 on 2024-02-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailto', models.CharField(max_length=100)),
                ('mail_from', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=100)),
            ],
        ),
    ]
