# Generated by Django 5.0.1 on 2024-02-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='mail_from',
            new_name='from_id',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='mailto',
            new_name='to',
        ),
    ]
