# Generated by Django 5.0.1 on 2024-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_india'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='about_place',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='india',
            name='place_features',
            field=models.TextField(max_length=200),
        ),
    ]
