# Generated by Django 5.0.1 on 2024-02-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_india_about_place_alter_india_place_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='india',
            new_name='kerala',
        ),
        migrations.RenameField(
            model_name='kerala',
            old_name='img',
            new_name='image_place',
        ),
    ]
