# Generated by Django 5.0.1 on 2024-02-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_travelguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelGuide',
        ),
    ]
