# Generated by Django 5.0.1 on 2024-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_travelguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='india',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_place', models.ImageField(upload_to='densinations1')),
                ('destination_name', models.CharField(max_length=100)),
                ('place_details', models.TextField(max_length=500)),
                ('features', models.TextField(max_length=200)),
            ],
        ),
    ]
