# Generated by Django 5.0.1 on 2024-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_india'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='img_place',
            field=models.ImageField(upload_to='densinations2'),
        ),
    ]
