# Generated by Django 5.0.1 on 2024-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_travelguide_destination_kerala_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_photo', models.ImageField(upload_to='guidephotos')),
                ('guide_name', models.CharField(max_length=255)),
                ('about_guide', models.TextField(max_length=400)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='user_name',
        ),
    ]
