# Generated by Django 5.0.1 on 2024-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_travelguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='about_guide',
            field=models.TextField(),
        ),
    ]
