# Generated by Django 5.0.1 on 2024-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_guide_about_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_image', models.ImageField(upload_to='guidephoto')),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_bio', models.CharField(max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
