# Generated by Django 5.0.1 on 2024-03-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
