# Generated by Django 5.0.1 on 2024-03-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_user_groups_remove_user_user_permissions_and_more'),
        ('user_app', '0016_alter_userprofile_users_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
