# Generated by Django 5.0.1 on 2024-03-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
