# Generated by Django 5.0.1 on 2024-03-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus',
        ),
    ]
