# Generated by Django 5.0.1 on 2024-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_img', models.ImageField(upload_to='busphotos')),
                ('bus_name', models.CharField(max_length=300)),
                ('seating_capacity', models.IntegerField()),
                ('bus_rent', models.IntegerField()),
            ],
        ),
    ]
