# Generated by Django 5.0.1 on 2024-03-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_busbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busbooking',
        ),
    ]
