# Generated by Django 5.0.1 on 2024-03-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_busbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_img', models.ImageField(upload_to='busphotos')),
                ('bus_name', models.CharField(max_length=300)),
                ('ac_or_non_ac', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('bus_rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('phonenum', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('numof_persons', models.IntegerField()),
                ('address', models.TextField()),
                ('pickup_date', models.DateTimeField()),
                ('picup_at', models.CharField(max_length=200)),
                ('drop_date', models.DateTimeField()),
                ('drop_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Busbooking',
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='choose_vehicles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicles'),
        ),
    ]
