# Generated by Django 5.0.1 on 2024-03-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
