# Generated by Django 5.0.1 on 2024-03-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
