# Generated by Django 5.0.1 on 2024-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
