# Generated by Django 5.0.1 on 2024-03-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0049_customuser_guide_profile_user_delete_profile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Userprofile',
        ),
        migrations.DeleteModel(
            name='FavoritePlace',
        ),
    ]
