# Generated by Django 5.0.1 on 2024-03-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0050_rename_customuser_userprofile_delete_favoriteplace'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userprofile',
            new_name='CustomUser',
        ),
    ]
