# Generated by Django 5.0.1 on 2024-03-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_user_reg_remove_customuser_groups_and_more'),
        ('guide_app', '0019_remove_booking_guide_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
