# Generated by Django 5.0.1 on 2024-03-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_delete_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_photo', models.ImageField(upload_to='guidephotos')),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_email', models.EmailField(max_length=254)),
                ('about_guide', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
