# Generated by Django 5.0.1 on 2024-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_username', models.CharField(max_length=100)),
                ('g_gender', models.CharField(max_length=10)),
                ('g_place', models.CharField(max_length=100)),
                ('g_email', models.EmailField(max_length=254, unique=True)),
                ('g_password1', models.CharField(max_length=100)),
                ('g_password2', models.CharField(max_length=100)),
            ],
        ),
    ]
