# Generated by Django 5.0.1 on 2024-03-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_guide_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide_reg',
            old_name='g_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='guide_reg',
            old_name='g_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='guide_reg',
            old_name='g_password1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='guide_reg',
            old_name='g_password2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='guide_reg',
            old_name='g_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='guide_reg',
            old_name='g_username',
            new_name='username',
        ),
    ]
