# Generated by Django 5.0.1 on 2024-03-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rename_g_email_guide_reg_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelGuide',
        ),
    ]
