# Generated by Django 5.0.1 on 2024-03-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_delete_travelguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guide_reg',
        ),
        migrations.DeleteModel(
            name='User_reg',
        ),
    ]
