# Generated by Django 5.0.1 on 2024-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_delete_guide_reg_delete_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
