# Generated by Django 5.0.1 on 2024-04-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_popular_is_favorite'),
        ('guide_app', '0026_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popular',
        ),
    ]
