# Generated by Django 5.0.1 on 2024-04-01 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_delete_popular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations')),
                ('place_name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=400)),
                ('features', models.TextField(max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('logged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
