# Generated by Django 5.0.1 on 2024-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_remove_popular_logged_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='popular',
            name='features',
            field=models.TextField(max_length=300),
        ),
    ]
