# Generated by Django 5.0.1 on 2024-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_popular_about_alter_popular_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='about',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='popular',
            name='features',
            field=models.TextField(max_length=500),
        ),
    ]
