# Generated by Django 5.0.1 on 2024-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_popular_about_alter_popular_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='india',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kerala',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
