# Generated by Django 5.0.1 on 2024-04-07 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_india_is_favorite_kerala_is_favorite'),
        ('user_app', '0049_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.popular')),
                ('destination2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.india')),
                ('destination3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kerala')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_reg')),
            ],
        ),
    ]
