# Generated by Django 5.0.1 on 2024-04-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_favorite'),
        ('user_app', '0049_user_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebooking',
            name='yourname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_reg'),
        ),
    ]
