# Generated by Django 5.0.1 on 2024-04-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_vehiclebooking_yourname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebooking',
            name='yourname',
            field=models.CharField(max_length=100),
        ),
    ]
