# Generated by Django 5.0.1 on 2024-04-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_vehiclebooking_yourname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Train',
        ),
    ]
