# Generated by Django 5.0.1 on 2024-04-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_delete_train'),
        ('user_app', '0049_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField()),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainclass')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_reg')),
            ],
        ),
    ]
