# Generated by Django 5.0.1 on 2024-04-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_train'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiclebooking',
        ),
    ]
