# Generated by Django 5.0.1 on 2024-04-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_delete_vehiclebooking'),
        ('user_app', '0049_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiclebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('phonenum', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('numof_persons', models.IntegerField()),
                ('address', models.TextField()),
                ('pickup_date', models.DateTimeField()),
                ('picup_at', models.CharField(max_length=200)),
                ('drop_date', models.DateTimeField()),
                ('drop_at', models.CharField(max_length=200)),
                ('choose_vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicles')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_reg')),
            ],
        ),
    ]
