# Generated by Django 5.0.1 on 2024-03-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_travelguide_destination_kerala_and_more'),
        ('user_app', '0003_favorite_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('Select_india_destinations', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.india')),
                ('Select_kerala_destinations', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.kerala')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travelguide')),
                ('select_Popular_destinations', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.popular')),
            ],
        ),
    ]
