# Generated by Django 5.0.1 on 2024-03-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_booking_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
