# Generated by Django 5.0.1 on 2024-03-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_travelguide'),
        ('user_app', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Select_india_destinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.india'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Select_kerala_destinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kerala'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='select_Popular_destinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.popular'),
        ),
    ]
