# Generated by Django 5.0.1 on 2024-03-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_booking_select_india_destinations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
