# Generated by Django 5.0.1 on 2024-03-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='place_photo',
        ),
    ]
