# Generated by Django 5.0.1 on 2024-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_remove_review_place_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='opinion',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
