# Generated by Django 5.0.1 on 2024-03-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_user'),
        ('user_app', '0014_rename_user_userprofile_users_name_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='users_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
