# Generated by Django 5.0.1 on 2024-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_userprofile_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='users_name',
            field=models.CharField(max_length=200),
        ),
    ]
