# Generated by Django 5.0.1 on 2024-03-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
    ]
