# Generated by Django 5.0.1 on 2024-03-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_rename_email_id_users_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
