# Generated by Django 5.0.1 on 2024-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_reg',
        ),
    ]
