# Generated by Django 5.0.1 on 2024-04-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_user_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
