# Generated by Django 5.0.1 on 2024-04-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0034_direct_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direct_message',
        ),
    ]
