# Generated by Django 5.0.1 on 2024-04-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0037_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
