# Generated by Django 5.0.1 on 2024-04-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0040_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='profile_image',
        ),
    ]
