# Generated by Django 5.0.1 on 2024-04-06 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0043_user_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_reg'),
        ),
    ]
