# Generated by Django 5.0.1 on 2024-04-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0044_remove_user_reg_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
