# Generated by Django 5.0.1 on 2024-04-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0046_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
